version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"  # El frontend se expone en localhost:3000
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:80"  # El backend se expone en localhost:4000
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
